version: '3.8'

services:
  backend:
    build:
      context: ./backend       # backend papkasi
      dockerfile: Dockerfile   # Dockerfile nomi
    container_name: renessans-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./frontend      # frontend papkasi
      dockerfile: Dockerfile   # Dockerfile nomi
    container_name: renessans-frontend
    ports:
      - "8080:80"
    restart: always

