name: CI/CD Render

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Docker Compose v2 ni ishlatamiz
      - name: Build images
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Wait backend
        run: sleep 8

      - name: Healthcheck backend
        run: curl -f http://localhost:3000/api/health

  deploy:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Deploy to Render
        uses: render-examples/deploy-to-render@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}

